Setup Client
CraftAcademy/slowfood-client-team-3 pull request #1
Opened 2020-03-02 16:49 UTC by johanbounce

Initial setup for client.
Configured:
• Semaphore
• Netlify
• Coveralls
• Cypress
• Jest and Enzyme
• Clean up files we don't  need

2020-03-03 14:18 UTC, johanbounce commented
Please state if something is missing. We can't find anything missing for the initial setup.

2020-03-04 13:37 UTC, faraznaeem requested changes
Dont understand what this PR does, please clarify

2020-03-04 13:37 UTC, faraznaeem commented on src/index.js
> +
delete comments

2020-03-05 08:30 UTC, johanbounce commented on src/index.js
> +
Basically forking and cloning the repo. Setting up (also making sure it's set up) all the tools such as Semaphore, Coveralls etc. that was included as user stories by oliver in the PT.

2020-03-05 12:44 UTC, johanbounce commented on src/index.js
> +
Comment is deleted

2020-03-05 12:49 UTC, closed without merging